version: '3'

volumes:
  local_postgres_data: {}

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        usedevdependancies: 1
    image: eth-oracle
    container_name: eth-oracle
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - .env
    network_mode: "host"
    command: bash -c "python oracle/main.py"
  postgres:
    image: postgres:latest
    container_name: backend_postgres
    ports:
      - "5432:5432"
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
